services:

  _base:
    env_file: .env
    image: clr_ws
    build:
      context: .
      dockerfile: Dockerfile
      target: er4-demo
      args:
        # WARNING: Changing username requires updating workspace mounts below.
        # Do not mess with these unless you know what you are doing!
        - USERNAME=er4-user
        - USER_UID=${USER_UID:-1000}
        - USER_GID=${USER_GID:-1000}
        - CLR_WS_BASE_IMAGE_TAG=${CLR_WS_BASE_IMAGE_TAG:-jazzy-devel}
    init: true
    stdin_open: true
    tty: true
    # WARNING: We set these by default but they may be trimmed down or removed depending on the exact nature
    # of the application.
    privileged: true
    network_mode: host
    # If using an nvidia driver uncomment these lines
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
    environment:
      # Pass the ROS_DOMAIN_ID from the host, if available, otherwise we default to 1 to avoid spamming networks
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-1}
      # Enable running graphical applications from inside the container
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      # This service will attempt to mount and use the DDS configuration from the host, if it is defined.
      # Otherwise, it will fall back to localhost only configuration using cyclonedds.
      - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
      - CYCLONEDDS_URI=/cyclonedds.xml
      - FASTRTPS_DEFAULT_PROFILES_FILE=/fastdds.xml
      # make the bash history folder link to our local .bash so that we can retain info between container starts
      - HISTFILE=/home/er4-user/.bash/.bash_history
      # default to colorized output of ros logs
      - RCUTILS_COLORIZED_OUTPUT=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      # Temporarily needed to build RoboPlan's OInK solver
      # See https://github.com/tier4/osqp_vendor/issues/26
      - CMAKE_POLICY_VERSION_MINIMUM=3.5
    volumes:
      # If they are present, mount DDS configurations from the host machine into the container.
      # If not, fallback to the default localhost configurations for both fastrtps and cyclonedds.
      - ${CYCLONEDDS_URI:-./config/cyclonedds.xml}:/cyclonedds.xml:ro
      - ${FASTRTPS_DEFAULT_PROFILES_FILE:-./config/fastdds.xml}:/fastdds.xml:ro
      # mount .bash to preserve history and config
      - ./.bash:/home/er4-user/.bash
      # Uncomment to allow access to host hardware
      # NOTE: This is quite dangerous so be careful with these containers
      # - /dev:/dev
      # For rendering graphical commands inside the container. The container requires `connect`
      # access to the socket so `ro` access should be sufficient. However, mismatched user information
      # or other socket permissions errors can cause other issues. Refer to the troubleshooting
      # documentation or ask if you are running into odd X issues.
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - $HOME/.Xauthority:/home/er4-user/.Xauthority:ro

  demo:
    extends: _base
    command: sleep infinity

  dev:
    extends: _base
    image: clr_ws_dev
    build:
      target: er4-dev
    volumes:
      # If you build this locally with the correct user information then this shouldn't be an issue
      # mounting without bindfs
      - ./src:/home/er4-user/ws/src/:rw
      # Bind mount folders into the container for preserving build artifacts
      - ./install:/home/er4-user/ws/install/:rw
      - ./build:/home/er4-user/ws/build/:rw
      - ./log:/home/er4-user/ws/log/:rw
      - ./.ccache:/home/er4-user/.ccache
    command: sleep infinity
    profiles: [dev]

  # The hardware services include any additional specifications for running on CLR hardware.
  hw-demo:
    extends: _base
    # Ensures the UR drivers have access to RT priority
    ulimits:
      rtprio: 99
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /dev:/dev
    command: sleep infinity
    profiles: [ hw-demo ]

  hw-dev:
    extends: dev
    # Ensures the UR drivers have access to RT priority
    ulimits:
      rtprio: 99
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /dev:/dev
    command: sleep infinity
    profiles: [ hw-dev ]
